### ISSUE TITLE
С bindings

### ISSUE THREAD

**Issue by cruelbob** [WebThingsIO/webthing-rust#41]
C is one of the most popular languages. It would be great to have C bindingins to this crate.

**Comment by bewee** [comment]
I had a try at this: [https://github.com/bewee/webthing-c](https://github.com/bewee/webthing-c)

Should we keep it as an own repo or somehow integrate it within this one?

Disclaimer: I am completely new to Rust, started learning only about a month ago. So I would be incredibly glab for feedback/suggestions/... of any kind :)

**Comment by tim-hellhake** [comment]
Cool! I wasn't aware of this.

> Should we keep it as an own repo or somehow integrate it within this one?

I prefer a separate repository.

I'm closing the issue since there is already an excellent example of using it in C.
