### ISSUE TITLE
Add MIT license

### ISSUE THREAD

**Issue by Luni-4** [WebThingsIO/webthing-rust#65]
Is it possible to add the MIT license alongside the MPL-2 one? If it is not possible, can at least the examples be re-licensed with MIT? 

Thanks in advance for the reply! :)

**Comment by benfrancis** [comment]
Hi @Luni-4, re-licensing would require permission from all copyright owners which includes all 9 contributors, plus Mozilla.

Most of the projects under the WebThings umbrella are licensed under MPL-2.0. What's your reason for wanting a license change?

Thanks

**Comment by Luni-4** [comment]
Hi @benfrancis

I would like to import most of the code contained in the examples inside a MIT project, but it seems I cannot do that without re-licensing the code. So I do have to rewrite the lamp Thing in another way in order to be compliant.

**Comment by benfrancis** [comment]
Hi @Luni-4,

The purpose of the examples is to be re-used, so I really wouldn't worry about it, they're more like documentation. Copy and paste away!

(IANAL).

**Comment by Luni-4** [comment]
Perfect! Thanks a lot @benfrancis! :)
